# Generated by Django 5.2 on 2025-04-20 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('optimized_file', models.FileField(blank=True, null=True, upload_to='optimized_resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Professional', 'Professional'), ('Creative', 'Creative'), ('Technical', 'Technical')], default='Professional', max_length=50)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
