# Generated by Django 5.2 on 2025-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
