# Generated by Django 5.2 on 2025-04-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
    ]
