# Generated by Django 5.2 on 2025-04-07 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_resume_feedback_remove_resume_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
