# Generated by Django 5.2 on 2025-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resume_feedback_resume_uploaded_at_alter_resume_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Professional', 'Professional'), ('Creative', 'Creative'), ('Technical', 'Technical')], default='Professional', max_length=50)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
